# Data Preparation

Loading the three datasets that power this project: VCDB for confirmed breach incidents, CISA KEV for known exploited vulnerabilities, and CyberEvents for broader incident coverage through 2026.

In [3]:
import pandas as pd
import numpy as np

In [4]:
vcdb = pd.read_csv("vcdb.csv", low_memory= False)
kev  = pd.read_csv('known_exploited_vulnerabilities.csv')
cyb  = pd.read_csv('cyber_events_2026-04-16.csv',low_memory= False)

In [5]:

kev.shape

(1568, 11)

In [6]:
cyb.shape

(16729, 44)

In [7]:
vcdb.shape

(10586, 2683)

In [8]:
vcdb.head()

,action.environmental.notes,action.environmental.variety.Deterioration,action.environmental.variety.Earthquake,action.environmental.variety.EMI,action.environmental.variety.ESD,action.environmental.variety.Fire,action.environmental.variety.Flood,action.environmental.variety.Hazmat,action.environmental.variety.Humidity,action.environmental.variety.Hurricane,...,pattern.Basic Web Application Attacks,pattern.System Intrusion,pattern.Social Engineering,pattern.Denial of Service,pattern.Everything Else,actor.Multiple,Actor,victim.industry2.31_33,victim.industry2.44_45,victim.industry2.48_49
0,NaN,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,Internal,False,False,False
1,NaN,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,Internal,False,False,False
2,NaN,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,External,False,False,False
3,NaN,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,Partner,False,False,False
4,NaN,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,External,False,False,False

In [9]:
cyb.head()

,slug,original_method,event_date,reported_date,year,month,actor,actor_type,organization,industry_code,...,opec,gulf_coop,g7,g20,aukus,csto,oecd,osce,five_eyes,change_log
0,p3v8m1r7k4x9t2q6,1,2026-03-31,4/1/2026,2026,3,Undetermined,Undetermined,Town of Pepperell,92,...,0,0,1,1,1,0,1,1,1,NaN
1,q7m2x9k4d1r8v5np,1,2026-03-31,3/31/2026,2026,3,UNC1069,Nation-State,Axios Javascript Client Library,51,...,0,0,1,1,1,0,1,1,1,NaN
2,q7e4m1n8p2k5r9t3,1,2026-03-30,3/30/2026,2026,3,XP95,Criminal,Eholo Health,51,...,0,0,0,0,0,0,1,1,0,NaN
3,h9u3i1o7p4a8s2df,0,2026-03-29,3/29/2026,2026,3,Undetermined,Hobbyist,Scotia-Glenville Central School District Faceb...,61,...,0,0,1,1,1,0,1,1,1,NaN
4,m4v8c2x7z1b9n5q6,1,2026-03-29,3/30/2026,2026,3,XP95,Criminal,Statistics South Africa,92,...,0,0,0,1,0,0,0,0,0,NaN

In [10]:
kev.head()

,cveID,vendorProject,product,vulnerabilityName,dateAdded,shortDescription,requiredAction,dueDate,knownRansomwareCampaignUse,notes,cwes
0,CVE-2009-0238,Microsoft,Office,Microsoft Office Remote Code Execution,2026-04-14,Microsoft Office Excel contains a remote code ...,"Apply mitigations per vendor instructions, fol...",2026-04-28,Unknown,https://learn.microsoft.com/en-us/security-upd...,CWE-94
1,CVE-2026-32201,Microsoft,SharePoint Server,Microsoft SharePoint Server Improper Input Val...,2026-04-14,Microsoft SharePoint Server contains an improp...,"Apply mitigations per vendor instructions, fol...",2026-04-28,Unknown,https://msrc.microsoft.com/update-guide/en-US/...,CWE-20
2,CVE-2012-1854,Microsoft,Visual Basic for Applications (VBA),Microsoft Visual Basic for Applications Insecu...,2026-04-13,Microsoft Visual Basic for Applications (VBA) ...,"Apply mitigations per vendor instructions, fol...",2026-04-27,Unknown,https://learn.microsoft.com/en-us/security-upd...,CWE-426
3,CVE-2025-60710,Microsoft,Windows,Microsoft Windows Link Following Vulnerability,2026-04-13,Microsoft Windows contains a link following vu...,"Apply mitigations per vendor instructions, fol...",2026-04-27,Unknown,https://msrc.microsoft.com/update-guide/vulner...,CWE-59
4,CVE-2023-21529,Microsoft,Exchange Server,Microsoft Exchange Server Deserialization of U...,2026-04-13,Microsoft Exchange Server contains a deseriali...,"Apply mitigations per vendor instructions, fol...",2026-04-27,Unknown,https://msrc.microsoft.com/update-guide/vulner...,CWE-502

## Data Types and Key Columns

Checking data types and summary stats on the columns I'll be using most. Wanted to confirm year and records-exposed came in as numbers, not strings.

In [11]:
vcdb[['timeline.incident.year', 'attribute.confidentiality.data_total',
      'victim.industry.name', 'actor.External', 'actor.Internal',
      'action.Malware', 'action.Hacking', 'action.Social',
      'action.malware.variety.Ransomware', 'action.social.variety.Phishing',
      'action.hacking.variety.Use of stolen creds',
      'discovery_method.External', 'discovery_method.Internal',
      'security_incident.Confirmed']].info()

<class 'pandas.DataFrame'>
RangeIndex: 10586 entries, 0 to 10585
Data columns (total 14 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   timeline.incident.year                      10586 non-null  int64
 1   attribute.confidentiality.data_total        5397 non-null   float64
 2   victim.industry.name                        10586 non-null  str
 3   actor.External                              10586 non-null  bool
 4   actor.Internal                              10586 non-null  bool
 5   action.Malware                              10586 non-null  bool
 6   action.Hacking                              10586 non-null  bool
 7   action.Social                               10586 non-null  bool
 8   action.malware.variety.Ransomware           10586 non-null  bool
 9   action.social.variety.Phishing              10586 non-null  bool
 10  action.hacking.variety.Use of stolen creds  10586 non-null  bool
 11  discovery_method.External                   10586 non-null  bool
 12  discovery_method.Internal                   10586 non-null  bool
 13  security_incident.Confirmed                 10586 non-null  bool
dtypes: bool(11), float64(1), int64(1), str(1)
memory usage: 362.0 KB

In [12]:
kev.info()

<class 'pandas.DataFrame'>
RangeIndex: 1568 entries, 0 to 1567
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   cveID                       1568 non-null   str
 1   vendorProject               1568 non-null   str
 2   product                     1568 non-null   str
 3   vulnerabilityName           1568 non-null   str
 4   dateAdded                   1568 non-null   str
 5   shortDescription            1568 non-null   str
 6   requiredAction              1568 non-null   str
 7   dueDate                     1568 non-null   str
 8   knownRansomwareCampaignUse  1568 non-null   str
 9   notes                       1568 non-null   str
 10  cwes                        1401 non-null   str
dtypes: str(11)
memory usage: 134.9 KB

In [13]:
cyb.info()

<class 'pandas.DataFrame'>
RangeIndex: 16729 entries, 0 to 16728
Data columns (total 44 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   slug             16729 non-null  str
 1   original_method  16729 non-null  int64
 2   event_date       16729 non-null  str
 3   reported_date    2175 non-null   str
 4   year             16729 non-null  int64
 5   month            16729 non-null  int64
 6   actor            16729 non-null  str
 7   actor_type       16729 non-null  str
 8   organization     16729 non-null  str
 9   industry_code    16729 non-null  int64
 10  industry         16729 non-null  str
 11  motive           16729 non-null  str
 12  event_type       16729 non-null  str
 13  event_subtype    16729 non-null  str
 14  magnitude        830 non-null    str
 15  duration         806 non-null    str
 16  scope            832 non-null    str
 17  ip               1514 non-null   str
 18  org_data         1477 non-null   str
 19  cust_data        1499 non-null   str
 20  description      16728 non-null  str
 21  source_url       16725 non-null  str
 22  country          16729 non-null  str
 23  actor_country    16729 non-null  str
 24  state            7939 non-null   str
 25  county           7759 non-null   str
 26  nato             16729 non-null  int64
 27  eu               16729 non-null  int64
 28  shanghai_coop    16729 non-null  int64
 29  oas              16729 non-null  int64
 30  mercosur         16729 non-null  int64
 31  au               16729 non-null  int64
 32  ecowas           16729 non-null  int64
 33  asean            16729 non-null  int64
 34  opec             16729 non-null  int64
 35  gulf_coop        16729 non-null  int64
 36  g7               16729 non-null  int64
 37  g20              16729 non-null  int64
 38  aukus            16729 non-null  int64
 39  csto             16729 non-null  int64
 40  oecd             16729 non-null  int64
 41  osce             16729 non-null  int64
 42  five_eyes        16729 non-null  int64
 43  change_log       16382 non-null  str
dtypes: int64(21), str(23)
memory usage: 5.6 MB

## Distributions

Looking at how incidents are spread across industries, years, actor types, and motives. This helps me spot anything obviously wrong before cleaning.

In [14]:
vcdb[['timeline.incident.year', 'attribute.confidentiality.data_total']].describe()

       timeline.incident.year  attribute.confidentiality.data_total
count            10586.000000                          5.397000e+03
mean              2015.107784                          2.277802e+07
std                  4.155231                          6.398620e+08
min               1971.000000                          1.000000e+00
25%               2012.000000                          2.500000e+01
50%               2014.000000                          1.362000e+03
75%               2017.000000                          2.820900e+04
max               2025.000000                          4.000000e+10

In [15]:
vcdb['victim.industry.name'].value_counts()

victim.industry.name
Healthcare         2560
Public             2403
Educational        1155
Finance             980
Information         875
Retail              529
Professional        486
Manufacturing       268
Unknown             231
Other Services      218
Administrative      196
Accomodation        173
Transportation      141
Trade               100
Entertainment        91
Real Estate          55
Utilities            47
Construction         32
Mining               26
Management           15
Agriculture           5
Name: count, dtype: int64

In [16]:
vcdb['timeline.incident.year'].value_counts().sort_index()

timeline.incident.year
1971       1
1984       2
1994       1
1995       1
1998       1
1999       2
2000       1
2001       5
2002       6
2003      13
2004      17
2005      23
2006      23
2007      51
2008      82
2009      94
2010     588
2011     547
2012    1277
2013    1939
2014    1011
2015     926
2016     867
2017     621
2018     362
2019     357
2020     344
2021     186
2022     117
2023     855
2024     104
2025     162
Name: count, dtype: int64

In [17]:
kev['vendorProject'].value_counts().head(10)

vendorProject
Microsoft    368
Apple         93
Cisco         86
Adobe         78
Google        71
Oracle        42
Apache        38
Ivanti        33
Fortinet      26
VMware        26
Name: count, dtype: int64

In [18]:
kev['knownRansomwareCampaignUse'].value_counts()

knownRansomwareCampaignUse
Unknown    1255
Known       313
Name: count, dtype: int64

In [19]:
cyb['actor_type'].value_counts()

actor_type
Criminal        12314
Hacktivist       2169
Nation-State     1195
Undetermined      813
Hobbyist          207
Terrorist          31
Name: count, dtype: int64

In [20]:
cyb['event_type'].value_counts()

event_type
Exploitive      8621
Disruptive      5126
Mixed           2768
Undetermined     214
Name: count, dtype: int64

In [21]:
cyb['motive'].value_counts()

motive
Financial                                   9677
Undetermined                                3495
Protest                                     1929
Political-Espionage                          914
Sabotage                                     462
Industrial-Espionage                         113
Personal Attack                               93
Political-espionage                           26
Reputation                                    12
Political-Espionage,Industrial-Espionage       4
Political-Espionage,Sabotage                   2
Protest,Political-Espionage                    1
Protest,Financial                              1
Name: count, dtype: int64

## Missing Data

Checking missingness across all three datasets. The big one here is `attribute.confidentiality.data_total` in VCDB -- only about half of incidents have a records-exposed value, which will matter for the breach size analysis later.

In [22]:
# VCDB key columns only
key_cols = ['timeline.incident.year', 'attribute.confidentiality.data_total',
            'victim.industry.name', 'actor.External', 'actor.Internal',
            'action.malware.variety.Ransomware', 'security_incident.Confirmed']
vcdb[key_cols].isna().sum()

timeline.incident.year                     0
attribute.confidentiality.data_total    5189
victim.industry.name                       0
actor.External                             0
actor.Internal                             0
action.malware.variety.Ransomware          0
security_incident.Confirmed                0
dtype: int64

In [23]:
kev.isna().sum()

cveID                           0
vendorProject                   0
product                         0
vulnerabilityName               0
dateAdded                       0
shortDescription                0
requiredAction                  0
dueDate                         0
knownRansomwareCampaignUse      0
notes                           0
cwes                          167
dtype: int64

In [24]:
cyb.isna().sum().sort_values(ascending=False)

duration           15923
magnitude          15899
scope              15897
org_data           15252
cust_data          15230
ip                 15215
reported_date      14554
county              8970
state               8790
change_log           347
source_url             4
description            1
motive                 0
industry               0
industry_code          0
organization           0
actor_type             0
actor                  0
month                  0
year                   0
event_date             0
original_method        0
slug                   0
event_subtype          0
actor_country          0
country                0
nato                   0
event_type             0
eu                     0
shanghai_coop          0
mercosur               0
oas                    0
ecowas                 0
asean                  0
opec                   0
au                     0
gulf_coop              0
g7                     0
aukus                  0
g20                    0
csto                   0
oecd                   0
osce                   0
five_eyes              0
dtype: int64

## Duplicate Check

Making sure there are no repeated rows before I start filtering.

In [25]:
cyb.duplicated().sum()

np.int64(3)

In [26]:
vcdb.duplicated().sum()

np.int64(2)

In [27]:
kev.duplicated().sum()

np.int64(0)

## Cleaning

Dropping duplicates, keeping only confirmed incidents, and filtering VCDB to reasonable years. I'm not imputing the missing records-exposed values since the missingness isn't random -- I'll just flag it in the analysis.

In [28]:
# Cleaning
vcdb = vcdb.drop_duplicates()

In [29]:
vcdb = vcdb[vcdb['security_incident.Confirmed'] == True]

In [30]:
vcdb = vcdb[vcdb['timeline.incident.year'].between(2000, 2025)]

In [31]:
print("Rows with records exposed data:", vcdb['attribute.confidentiality.data_total'].notna().sum())
print("Rows without:", vcdb['attribute.confidentiality.data_total'].isna().sum())

Rows with records exposed data: 5366
Rows without: 5128

## KEV Date Parsing

Converting the date column to datetime and pulling out the year so I can do year-level trend analysis.

In [32]:
kev['dateAdded'] = pd.to_datetime(kev['dateAdded'])

In [33]:
kev['year_added'] = kev['dateAdded'].dt.year

In [34]:
print(kev['knownRansomwareCampaignUse'].value_counts())

knownRansomwareCampaignUse
Unknown    1255
Known       313
Name: count, dtype: int64

## CyberEvents Cleaning

Dropping duplicates on the slug column since that's the unique identifier. Also standardizing the motive field -- it had casing inconsistencies that would have created duplicate categories.

In [35]:
cyb = cyb.drop_duplicates(subset='slug')

In [36]:
cyb['event_date'] = pd.to_datetime(cyb['event_date'])

In [37]:
cyb['motive'] = cyb['motive'].str.strip().str.title()
print(cyb['motive'].value_counts())

motive
Financial                                   9675
Undetermined                                3494
Protest                                     1929
Political-Espionage                          940
Sabotage                                     462
Industrial-Espionage                         113
Personal Attack                               93
Reputation                                    12
Political-Espionage,Industrial-Espionage       4
Political-Espionage,Sabotage                   2
Protest,Political-Espionage                    1
Protest,Financial                              1
Name: count, dtype: int64

In [38]:
print(cyb['motive'].value_counts())

motive
Financial                                   9675
Undetermined                                3494
Protest                                     1929
Political-Espionage                          940
Sabotage                                     462
Industrial-Espionage                         113
Personal Attack                               93
Reputation                                    12
Political-Espionage,Industrial-Espionage       4
Political-Espionage,Sabotage                   2
Protest,Political-Espionage                    1
Protest,Financial                              1
Name: count, dtype: int64

## Dropping Sparse Columns

These columns had over 90% missingness and weren't relevant to my research questions, so I dropped them rather than carry the noise forward.

In [39]:
cols_to_drop = ['magnitude', 'duration', 'scope', 'ip', 'org_data', 'cust_data', 'reported_date']
cyb = cyb.drop(columns=cols_to_drop)

In [40]:
print("Remaining columns:", cyb.shape[1])

Remaining columns: 37

In [41]:
vcdb.shape

(10494, 2683)

In [42]:
kev.shape

(1568, 12)

In [43]:
cyb.shape

(16726, 37)

In [44]:
ransomware = vcdb[vcdb['action.malware.variety.Ransomware'] == True]
print("Ransomware incidents:", len(ransomware))

Ransomware incidents: 1193

In [45]:
vcdb.loc[vcdb['timeline.incident.year'].between(2015, 2020), 
         ['timeline.incident.year', 'victim.industry.name', 'actor.External', 'action.malware.variety.Ransomware']].head(10)

,timeline.incident.year,victim.industry.name,actor.External,action.malware.variety.Ransomware
1,2020,Professional,False,False
7,2017,Healthcare,True,False
10,2018,Public,True,False
11,2016,Public,True,False
14,2017,Healthcare,False,False
16,2017,Healthcare,False,False
19,2016,Public,True,False
22,2015,Educational,True,False
23,2016,Finance,True,False
25,2016,Retail,False,False

In [46]:
kev['dateAdded']

0      2026-04-14
1      2026-04-14
2      2026-04-13
3      2026-04-13
4      2026-04-13
          ...
1563   2021-11-03
1564   2021-11-03
1565   2021-11-03
1566   2021-11-03
1567   2021-11-03
Name: dateAdded, Length: 1568, dtype: datetime64[us]

In [47]:
kev['dateAdded']= pd.to_datetime(kev['dateAdded'])
kev['dateAdded'].info()
cyb['event_date'] = pd.to_datetime(cyb['event_date'])
cyb['event_date'].info()

<class 'pandas.Series'>
RangeIndex: 1568 entries, 0 to 1567
Series name: dateAdded
Non-Null Count  Dtype
--------------  -----
1568 non-null   datetime64[us]
dtypes: datetime64[us](1)
memory usage: 12.4 KB
<class 'pandas.Series'>
Index: 16726 entries, 0 to 16728
Series name: event_date
Non-Null Count  Dtype
--------------  -----
16726 non-null  datetime64[us]
dtypes: datetime64[us](1)
memory usage: 261.3 KB

In [48]:
vcdb['timeline.incident.year'].value_counts().sort_values()

timeline.incident.year
2000       1
2001       4
2002       6
2003      13
2004      17
2006      23
2005      23
2007      51
2008      82
2009      94
2024     104
2022     116
2025     162
2021     186
2020     344
2018     357
2019     357
2011     545
2010     587
2017     611
2023     855
2016     860
2015     917
2014    1003
2012    1271
2013    1905
Name: count, dtype: int64

In [49]:
vcdb['attribute.confidentiality.data_total'].notna().groupby(vcdb['timeline.incident.year']).mean()

timeline.incident.year
2000    1.000000
2001    0.250000
2002    0.666667
2003    0.538462
2004    0.294118
2005    0.652174
2006    0.608696
2007    0.764706
2008    0.597561
2009    0.414894
2010    0.923339
2011    0.796330
2012    0.586939
2013    0.447769
2014    0.519442
2015    0.574700
2016    0.510465
2017    0.463175
2018    0.478992
2019    0.478992
2020    0.497093
2021    0.494624
2022    0.534483
2023    0.077193
2024    0.663462
2025    0.277778
Name: attribute.confidentiality.data_total, dtype: float64

In [50]:
kev.describe()

                        dateAdded   year_added
count                        1568  1568.000000
mean   2023-05-01 08:38:52.653061  2022.841199
min           2021-11-03 00:00:00  2021.000000
25%           2022-03-03 00:00:00  2022.000000
50%           2022-06-27 00:00:00  2022.000000
75%           2024-09-18 00:00:00  2024.000000
max           2026-04-14 00:00:00  2026.000000
std                           NaN     1.532765

In [51]:
kev.head()

,cveID,vendorProject,product,vulnerabilityName,dateAdded,shortDescription,requiredAction,dueDate,knownRansomwareCampaignUse,notes,cwes,year_added
0,CVE-2009-0238,Microsoft,Office,Microsoft Office Remote Code Execution,2026-04-14,Microsoft Office Excel contains a remote code ...,"Apply mitigations per vendor instructions, fol...",2026-04-28,Unknown,https://learn.microsoft.com/en-us/security-upd...,CWE-94,2026
1,CVE-2026-32201,Microsoft,SharePoint Server,Microsoft SharePoint Server Improper Input Val...,2026-04-14,Microsoft SharePoint Server contains an improp...,"Apply mitigations per vendor instructions, fol...",2026-04-28,Unknown,https://msrc.microsoft.com/update-guide/en-US/...,CWE-20,2026
2,CVE-2012-1854,Microsoft,Visual Basic for Applications (VBA),Microsoft Visual Basic for Applications Insecu...,2026-04-13,Microsoft Visual Basic for Applications (VBA) ...,"Apply mitigations per vendor instructions, fol...",2026-04-27,Unknown,https://learn.microsoft.com/en-us/security-upd...,CWE-426,2026
3,CVE-2025-60710,Microsoft,Windows,Microsoft Windows Link Following Vulnerability,2026-04-13,Microsoft Windows contains a link following vu...,"Apply mitigations per vendor instructions, fol...",2026-04-27,Unknown,https://msrc.microsoft.com/update-guide/vulner...,CWE-59,2026
4,CVE-2023-21529,Microsoft,Exchange Server,Microsoft Exchange Server Deserialization of U...,2026-04-13,Microsoft Exchange Server contains a deseriali...,"Apply mitigations per vendor instructions, fol...",2026-04-27,Unknown,https://msrc.microsoft.com/update-guide/vulner...,CWE-502,2026

In [52]:
kev.value_counts()

cveID           vendorProject  product                              vulnerabilityName                                                               dateAdded   shortDescription                                                                                                                                                                                                                    requiredAction                                                                                                                                                         dueDate     knownRansomwareCampaignUse  notes                                                                                                                                cwes     year_added
CVE-2009-0238   Microsoft      Office                               Microsoft Office Remote Code Execution                                          2026-04-14  Microsoft Office Excel contains a remote code execution vulnerability that could allow an attacker to take complete control of an affected system if a user opens a specially crafted Excel file that includes a malformed object.  Apply mitigations per vendor instructions, follow applicable BOD 22-01 guidance for cloud services, or discontinue use of the product if mitigations are unavailable.  2026-04-28  Unknown                     https://learn.microsoft.com/en-us/security-updates/securitybulletins/2009/ms09-009 ; https://nvd.nist.gov/vuln/detail/CVE-2009-0238  CWE-94   2026          1
CVE-2026-32201  Microsoft      SharePoint Server                    Microsoft SharePoint Server Improper Input Validation Vulnerability             2026-04-14  Microsoft SharePoint Server contains an improper input validation vulnerability that allows an unauthorized attacker to perform spoofing over a network.                                                                            Apply mitigations per vendor instructions, follow applicable BOD 22-01 guidance for cloud services, or discontinue use of the product if mitigations are unavailable.  2026-04-28  Unknown                     https://msrc.microsoft.com/update-guide/en-US/vulnerability/CVE-2026-32201 ; https://nvd.nist.gov/vuln/detail/CVE-2026-32201         CWE-20   2026          1
CVE-2012-1854   Microsoft      Visual Basic for Applications (VBA)  Microsoft Visual Basic for Applications Insecure Library Loading Vulnerability  2026-04-13  Microsoft Visual Basic for Applications (VBA) contains an insecure library loading vulnerability that could allow for remote code execution.                                                                                        Apply mitigations per vendor instructions, follow applicable BOD 22-01 guidance for cloud services, or discontinue use of the product if mitigations are unavailable.  2026-04-27  Unknown                     https://learn.microsoft.com/en-us/security-updates/securitybulletins/2012/ms12-046 ; https://nvd.nist.gov/vuln/detail/CVE-2012-1854  CWE-426  2026          1
CVE-2025-60710  Microsoft      Windows                              Microsoft Windows Link Following Vulnerability                                  2026-04-13  Microsoft Windows contains a link following vulnerability that allows for privilege escalation                                                                                                                                      Apply mitigations per vendor instructions, follow applicable BOD 22-01 guidance for cloud services, or discontinue use of the product if mitigations are unavailable.  2026-04-27  Unknown                     https://msrc.microsoft.com/update-guide/vulnerability/CVE-2025-60710 ; https://nvd.nist.gov/vuln/detail/CVE-2025-60710               CWE-59   2026          1
CVE-2023-21529  Microsoft      Exchange Server                      Microsoft Exchange Server Deserialization of Untrusted Data Vulnerability       2026-04-13  Microsoft Exchange Server contains a deserialization of untrusted data that allows an authenticated attacker to achieve remote code execution.                                                                                      Apply mitigations per vendor instructions, follow applicable BOD 22-01 guidance for cloud services, or discontinue use of the product if mitigations are unavailable.  2026-04-27  Unknown                     https://msrc.microsoft.com/update-guide/vulnerability/CVE-2023-21529 ; https://nvd.nist.gov/vuln/detail/CVE-2023-21529               CWE-502  2026          1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ..
CVE-2021-27561  Yealink        Device Management                    Yealink Device Management Server-Side Request Forgery (SSRF) Vulnerability      2021-11-03  Yealink Device Management contains a server-side request forgery (SSRF) vulnerability that allows for unauthenticated remote code execution.                                                                                        Apply updates per vendor instructions.                                                                                                                                 2021-11-17  Unknown                     https://nvd.nist.gov/vuln/detail/CVE-2021-27561                                                                                      CWE-78   2021          1
CVE-2021-40539  Zoho           ManageEngine                         Zoho ManageEngine ADSelfService Plus Authentication Bypass Vulnerability        2021-11-03  Zoho ManageEngine ADSelfService Plus contains an authentication bypass vulnerability affecting the REST API URLs which allow for remote code execution.                                                                             Apply updates per vendor instructions.                                                                                                                                 2021-11-17  Known                       https://nvd.nist.gov/vuln/detail/CVE-2021-40539                                                                                      CWE-55   2021          1
CVE-2020-10189  Zoho           ManageEngine                         Zoho ManageEngine Desktop Central File Upload Vulnerability                     2021-11-03  Zoho ManageEngine Desktop Central contains a file upload vulnerability that allows for unauthenticated remote code execution.                                                                                                       Apply updates per vendor instructions.                                                                                                                                 2022-05-03  Unknown                     https://nvd.nist.gov/vuln/detail/CVE-2020-10189                                                                                      CWE-502  2021          1
CVE-2019-8394   Zoho           ManageEngine                         Zoho ManageEngine ServiceDesk Plus (SDP) File Upload Vulnerability              2021-11-03  Zoho ManageEngine ServiceDesk Plus (SDP) contains an unspecified vulnerability that allows remote users to upload files via login page customization.                                                                               Apply updates per vendor instructions.                                                                                                                                 2022-05-03  Unknown                     https://nvd.nist.gov/vuln/detail/CVE-2019-8394                                                                                       CWE-434  2021          1
CVE-2020-29583  Zyxel          Multiple Products                    Zyxel Multiple Products Use of Hard-Coded Credentials Vulnerability             2021-11-03  Zyxel firewalls (ATP, USG, VM) and AP Controllers (NXC2500 and NXC5500) contain a use of hard-coded credentials vulnerability in an undocumented account ("zyfwp") with an unchangeable password.                                   Apply updates per vendor instructions.                                                                                                                                 2022-05-03  Unknown                     https://nvd.nist.gov/vuln/detail/CVE-2020-29583                                                                                      CWE-522  2021          1
Name: count, Length: 1401, dtype: int64

In [53]:
kev['knownRansomwareCampaignUse'].value_counts()

knownRansomwareCampaignUse
Unknown    1255
Known       313
Name: count, dtype: int64

In [54]:
cyb['motive'].value_counts()

motive
Financial                                   9675
Undetermined                                3494
Protest                                     1929
Political-Espionage                          940
Sabotage                                     462
Industrial-Espionage                         113
Personal Attack                               93
Reputation                                    12
Political-Espionage,Industrial-Espionage       4
Political-Espionage,Sabotage                   2
Protest,Political-Espionage                    1
Protest,Financial                              1
Name: count, dtype: int64

In [55]:

cyb['motive'] = cyb['motive'].str.strip().str.title()
cyb['motive'].value_counts()

motive
Financial                                   9675
Undetermined                                3494
Protest                                     1929
Political-Espionage                          940
Sabotage                                     462
Industrial-Espionage                         113
Personal Attack                               93
Reputation                                    12
Political-Espionage,Industrial-Espionage       4
Political-Espionage,Sabotage                   2
Protest,Political-Espionage                    1
Protest,Financial                              1
Name: count, dtype: int64

In [56]:
cyb['event_subtype'].value_counts()

event_subtype
Exploitation of Application Server                                                                           6005
Data Attack                                                                                                  2997
External Denial of Service                                                                                   1763
Exploitation of End Hosts                                                                                    1446
Message Manipulation                                                                                         1211
                                                                                                             ...
Internal Denial of Service,Exploitation of Application Server,Message Manipulation                              1
Message Manipulation,Exploitation of End Hosts,External Denial of Service,Exploitation of Data in Transit       1
Exploitation of Network Infrastructure,Internal Denial of Service                                               1
Message Manipulation,External Denial of Service,Internal Denial of Service, Physical Attack                     1
Data Attack,Exploitation of Application Server,Message Manipulation                                             1
Name: count, Length: 80, dtype: int64

In [57]:
key_cols = [
    'timeline.incident.year',
    'victim.industry.name',
    'actor.External',
    'attribute.confidentiality.data_total'

]
vcdb[key_cols].isna().mean()

timeline.incident.year                  0.00000
victim.industry.name                    0.00000
actor.External                          0.00000
attribute.confidentiality.data_total    0.48866
dtype: float64

In [58]:
hacking_variety_cols = vcdb.filter(like='action.hacking.variety.').columns

vcdb[hacking_variety_cols].isna().mean().sort_values(ascending=False)

action.hacking.variety.Abuse of functionality       0.0
action.hacking.variety.AitM                         0.0
action.hacking.variety.Backdoor                     0.0
action.hacking.variety.Brute force                  0.0
action.hacking.variety.Buffer overflow              0.0
action.hacking.variety.Cache poisoning              0.0
action.hacking.variety.Cryptanalysis                0.0
action.hacking.variety.CSRF                         0.0
action.hacking.variety.Disable controls             0.0
action.hacking.variety.DoS                          0.0
action.hacking.variety.Evade Defenses               0.0
action.hacking.variety.Exploit misconfig            0.0
action.hacking.variety.Exploit vuln                 0.0
action.hacking.variety.Forced browsing              0.0
action.hacking.variety.Format string attack         0.0
action.hacking.variety.Fuzz testing                 0.0
action.hacking.variety.Hijack                       0.0
action.hacking.variety.HTTP request smuggling       0.0
action.hacking.variety.HTTP request splitting       0.0
action.hacking.variety.HTTP response smuggling      0.0
action.hacking.variety.HTTP response splitting      0.0
action.hacking.variety.Insecure deserialization     0.0
action.hacking.variety.Integer overflows            0.0
action.hacking.variety.LDAP injection               0.0
action.hacking.variety.Mail command injection       0.0
action.hacking.variety.Null byte injection          0.0
action.hacking.variety.Offline cracking             0.0
action.hacking.variety.OS commanding                0.0
action.hacking.variety.Other                        0.0
action.hacking.variety.Pass-the-hash                0.0
action.hacking.variety.Path traversal               0.0
action.hacking.variety.Profile host                 0.0
action.hacking.variety.Prompt injection             0.0
action.hacking.variety.Reverse engineering          0.0
action.hacking.variety.RFI                          0.0
action.hacking.variety.Routing detour               0.0
action.hacking.variety.Scan network                 0.0
action.hacking.variety.Session fixation             0.0
action.hacking.variety.Session prediction           0.0
action.hacking.variety.Session replay               0.0
action.hacking.variety.Soap array abuse             0.0
action.hacking.variety.Special element injection    0.0
action.hacking.variety.SQLi                         0.0
action.hacking.variety.SSI injection                0.0
action.hacking.variety.Unknown                      0.0
action.hacking.variety.URL redirector abuse         0.0
action.hacking.variety.Use of stolen creds          0.0
action.hacking.variety.User breakout                0.0
action.hacking.variety.Virtual machine escape       0.0
action.hacking.variety.XML attribute blowup         0.0
action.hacking.variety.XML entity expansion         0.0
action.hacking.variety.XML external entities        0.0
action.hacking.variety.XML injection                0.0
action.hacking.variety.XPath injection              0.0
action.hacking.variety.XQuery injection             0.0
action.hacking.variety.XSS                          0.0
dtype: float64

In [59]:
action_social_variety = vcdb.filter(like='action.social.variety.').columns
vcdb[action_social_variety].isna().mean().sort_values(ascending=False)

action.social.variety.Baiting           0.0
action.social.variety.Bribery           0.0
action.social.variety.Elicitation       0.0
action.social.variety.Evade Defenses    0.0
action.social.variety.Extortion         0.0
action.social.variety.Forgery           0.0
action.social.variety.Influence         0.0
action.social.variety.Other             0.0
action.social.variety.Phishing          0.0
action.social.variety.Pretexting        0.0
action.social.variety.Prompt bombing    0.0
action.social.variety.Propaganda        0.0
action.social.variety.Scam              0.0
action.social.variety.Spam              0.0
action.social.variety.Unknown           0.0
dtype: float64

In [60]:
vcdb[['timeline.incident.year']].info()

<class 'pandas.DataFrame'>
Index: 10494 entries, 0 to 10585
Data columns (total 1 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   timeline.incident.year  10494 non-null  int64
dtypes: int64(1)
memory usage: 164.0 KB

In [61]:
kev['year'] = kev['dateAdded'].dt.year
kev['year'].value_counts().sort_index()

year
2021    311
2022    555
2023    187
2024    186
2025    245
2026     84
Name: count, dtype: int64

## Multi-Value Fields

Some rows in CyberEvents have multiple motives or subtypes in a single comma-separated string. Exploding these into separate rows lets me count each value properly without undercounting.

In [62]:
cyb_motive = cyb.copy()

cyb_motive['motive'] = cyb_motive['motive'].str.split(',')

cyb_motive = cyb_motive.explode('motive')

cyb_motive['motive'] = cyb_motive['motive'].str.strip()

In [63]:
cyb_motive.info()

<class 'pandas.DataFrame'>
Index: 16734 entries, 0 to 16728
Data columns (total 37 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   slug             16734 non-null  str
 1   original_method  16734 non-null  int64
 2   event_date       16734 non-null  datetime64[us]
 3   year             16734 non-null  int64
 4   month            16734 non-null  int64
 5   actor            16734 non-null  str
 6   actor_type       16734 non-null  str
 7   organization     16734 non-null  str
 8   industry_code    16734 non-null  int64
 9   industry         16734 non-null  str
 10  motive           16734 non-null  str
 11  event_type       16734 non-null  str
 12  event_subtype    16734 non-null  str
 13  description      16733 non-null  str
 14  source_url       16730 non-null  str
 15  country          16734 non-null  str
 16  actor_country    16734 non-null  str
 17  state            7938 non-null   str
 18  county           7757 non-null   str
 19  nato             16734 non-null  int64
 20  eu               16734 non-null  int64
 21  shanghai_coop    16734 non-null  int64
 22  oas              16734 non-null  int64
 23  mercosur         16734 non-null  int64
 24  au               16734 non-null  int64
 25  ecowas           16734 non-null  int64
 26  asean            16734 non-null  int64
 27  opec             16734 non-null  int64
 28  gulf_coop        16734 non-null  int64
 29  g7               16734 non-null  int64
 30  g20              16734 non-null  int64
 31  aukus            16734 non-null  int64
 32  csto             16734 non-null  int64
 33  oecd             16734 non-null  int64
 34  osce             16734 non-null  int64
 35  five_eyes        16734 non-null  int64
 36  change_log       16387 non-null  str
dtypes: datetime64[us](1), int64(21), str(15)
memory usage: 4.9 MB

In [64]:
cyb_subtype = cyb.copy()

cyb_subtype['event_subtype'] = cyb_subtype['event_subtype'].str.split(',')

cyb_subtype = cyb_subtype.explode('event_subtype')

cyb_subtype['event_subtype'] = cyb_subtype['event_subtype'].str.strip()
cyb_subtype

,slug,original_method,event_date,year,month,actor,actor_type,organization,industry_code,industry,...,opec,gulf_coop,g7,g20,aukus,csto,oecd,osce,five_eyes,change_log
0,p3v8m1r7k4x9t2q6,1,2026-03-31,2026,3,Undetermined,Undetermined,Town of Pepperell,92,Public Administration,...,0,0,1,1,1,0,1,1,1,NaN
1,q7m2x9k4d1r8v5np,1,2026-03-31,2026,3,UNC1069,Nation-State,Axios Javascript Client Library,51,Information,...,0,0,1,1,1,0,1,1,1,NaN
2,q7e4m1n8p2k5r9t3,1,2026-03-30,2026,3,XP95,Criminal,Eholo Health,51,Information,...,0,0,0,0,0,0,1,1,0,NaN
3,h9u3i1o7p4a8s2df,0,2026-03-29,2026,3,Undetermined,Hobbyist,Scotia-Glenville Central School District Faceb...,61,Educational Services,...,0,0,1,1,1,0,1,1,1,NaN
4,m4v8c2x7z1b9n5q6,1,2026-03-29,2026,3,XP95,Criminal,Statistics South Africa,92,Public Administration,...,0,0,0,1,0,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16724,3a94b8cf6dde1f66,1,2014-01-03,2014,1,DERP Trolling,Undetermined,Battle.net,51,Information,...,0,0,1,1,1,0,1,1,1,[2026-03-02 15:45:26] Pipeline run: parsed MM/...
16725,6100014f6ca84b3d,1,2014-01-02,2014,1,Undetermined,Criminal,Snapchat,51,Information,...,0,0,1,1,1,0,1,1,1,[2026-03-02 15:45:26] Pipeline run: parsed MM/...
16726,3bbe0695e2d019f3,1,2014-01-01,2014,1,Syrian Electronic Army,Hacktivist,Skype's Social Media,54,"Professional, Scientific, and Technical Services",...,0,0,1,1,1,0,1,1,1,[2026-03-02 15:45:26] Pipeline run: parsed MM/...
16727,ecac8b3e60a2f72f,1,2014-01-01,2014,1,Undetermined,Criminal,Record Assist LLC,54,"Professional, Scientific, and Technical Services",...,0,0,1,1,1,0,1,1,1,[2026-03-02 15:45:26] Pipeline run: parsed MM/...
16728,1f72c2eb8ab303e4,1,2014-01-01,2014,1,Undetermined,Criminal,Barry University,61,Educational Services,...,0,0,1,1,1,0,1,1,1,[2026-03-02 15:45:26] Pipeline run: parsed MM/...

## Save Clean Files

Writing the cleaned versions out to CSV so the analysis notebooks can load them directly without re-running all of this.

In [65]:
vcdb.to_csv('vcdb_clean.csv', index=False)
kev.to_csv('kev_clean.csv', index=False)
cyb.to_csv('cyb_clean.csv', index=False)